#!/usr/bin/env python

import clint
import sys
import os
import lucene
from textorganizer import config, select, view, indexfiles, searchfiles

class TextOrganizer:
    def __init__(self,lucenedir):
        self.lucenedir = lucenedir
        #lucene object containing selected documents
        self.scoreDocs = None
        #list of all terms in selected documents
        self.allTerms = None
        #dictionary containing TDM for selected documents        
        self.allDicts = None

    def parseargs(self,grouped_args):
        
        if '-a' in grouped_args:
            if len(grouped_args['-a']) == 1:
                add_files = True
            elif len(grouped_args['-a']) == 0:
                print 'Add_files flag passed, but no directory given. Ignoring -a flag.'
                add_files = False
            elif len(grouped_args['-a']) > 1:
                print 'Only one directory may be passed to txtorg -a. Ignoring -a flag.'
                add_files = False
        else:
            add_files = False

        if add_files:
            indexfiles.IndexFiles(grouped_args['-a'][0],self.lucenedir,lucene.StandardAnalyzer(lucene.Version.LUCENE_CURRENT))
        else:
            self.mainprompt()

    


    def mainprompt(self):
        print "Welcome message."
        while True:
        #present user with a prompt, grab input, and convert to lowercase
            instr=raw_input("> ").lower()

            if instr == 'q' or instr == 'quit' or instr == 'exit':
                break
            elif instr.startswith('select '):
                self.run_searcher(instr[7:])
            elif instr.startswith('export tdm'):
                self.export_tdm()
            elif instr.startswith('view '):
                viewdb = view.viewdb(instr[5:],configuration['dblocation'])
            elif instr.startswith('add '):
            #add.process_raw_files(FILENAMES,configuration['dblocation'])
            #need a good way to get a list of filenames from the interactive prompt
                print '\'add\' is not yet supported from the interactive prompt. Please use \'txtorg add [filename]\' from the shell.'
            else:
                print "Input not understood. Type 'h' or 'help' for help."

    def run_searcher(self,command):
        directory = lucene.SimpleFSDirectory(lucene.File(self.lucenedir))
        searcher = lucene.IndexSearcher(directory, True)
        reader = lucene.IndexReader.open(directory, True)
        analyzer = lucene.StandardAnalyzer(lucene.Version.LUCENE_CURRENT)

        self.scoreDocs, self.allTerms, self.allDicts = searchfiles.run(searcher, analyzer, reader, command)
        #Alex, you mentioned at the top of searchfiles.py that searcher.close() sometimes causes stack overflows, but it was not commented out. Did you fix this issue?

        searcher.close()

    def export_tdm(self):
        if (self.scoreDocs is None) or (self.allTerms is None) or (self.allDicts is None):
            print "Select documents with \"select [query]\" before exporting TDM"
            return False

        print "Choose a file for export (leave blank to accept default -> ./tdm.csv)"
        outfile = './tdm.csv'
        outfile_raw = raw_input()
        if outfile_raw == "":
            outfile = os.path.realpath(outfile)
        else:
            outfile = os.path.realpath(os.path.expanduser(outfile_raw))

        print "Exporting TDM to ", outfile
        searchfiles.writeTDM(self.allDicts, self.allTerms, outfile)
        
if __name__ == '__main__':
    lucene.initVM()
    print 'lucene', lucene.VERSION

    programdir = os.path.join(os.path.dirname(__file__))
    lucenedir = os.path.join(programdir,'lucene_index')

    main = TextOrganizer(lucenedir)
    main.parseargs(clint.args.grouped)
